### ISSUE TITLE
property-history returns empty strings for simple JSON fields

### ISSUE THREAD

**Issue by patrickmcelwee** [marklogic-community/smart-mastering-core#108]
I am about to file a PR for this.

We discovered that the sm-history-properties was returning empty-string keys for certain fields, when the merged field was were the result of simple JSON fields.

For example, it would return:

```
{
  ...,
  "PersonGender": {"": { ... } }
  ...
}
```

if the field in the document was simple:

```
{
  envelope: {
    headers: { ... },
    instance: {
      ...,
      "PersonGender": "F"
    }
  }
}
```

The desired result would have been:

```
{
  ...,
  "PersonGender": {"F": { ... } }
  ...
}
```

It did work for JSON fields where the value was an object.

**Comment by dmcassel** [comment]
@patrickmcelwee could you confirm that the `PersonSex` property in [this doc](https://github.com/marklogic-community/smart-mastering-core/blob/master/src/test/ml-modules/root/test/suites/merging-json/test-data/doc1.json) would trigger this bug?

**Comment by patrickmcelwee** [comment]
Yes, that field would trigger the bug

**Comment by dmcassel** [comment]
This should be fixed in dev, but it would be good to add a more comprehensive unit test.

**Comment by dmcassel** [comment]
Added more tests: https://github.com/marklogic-community/smart-mastering-core/pull/110
