### ISSUE TITLE
Documentation - Wrong Namespace in Merge Options

### ISSUE THREAD

**Issue by RobertSzkutak** [marklogic-community/smart-mastering-core#116]
See: https://marklogic-community.github.io/smart-mastering-core/docs/merging-options/

The namespace on the merge options sample is incorrect. It should instead be: `"http://marklogic.com/smart-mastering/merging"`

**Comment by dmcassel** [comment]
Hi @RobertSzkutak. Good catch -- we've actually fixed that on the `docs-next` branch, which will go live the next time we do a release.
