### ISSUE TITLE
MDMImport input flow output collections are in upper case

### ISSUE THREAD

**Issue by Mina78** [marklogic-community/smart-mastering-core#140]
The MDMImport input flow output collections are capitalized, like MDM-CONTENT, which makes the Harmonize flow fail. I think the collection name should be in lowercase like they are in the /com.marklogic.smart-mastering/constants.xqy

**Comment by dmcassel** [comment]
@Mina78 I just did a quick search and didn't find cases where MDM-CONTENT was capitalized. Could you provide a link to where you saw that?

**Comment by popzip** [comment]
@Mina78 are you blocked on this? we're unable to reproduce/find anywhere in code base with caps. feel free to contact us offline.
