### ISSUE TITLE
Missing documentation details regarding thesaurus use for matching

### ISSUE THREAD

**Issue by xbonnamy-marklogic** [marklogic-community/smart-mastering-core#207]
Matching options (https://marklogic-community.github.io/smart-mastering-core/docs/matching-options/) list the ability to use a thesaurus algorithm but there is not detail documentation regarding thesaurus document "actions" : should it be referenced using thsr:load, should it be just ingested in a specific collection, etc.

**Comment by dmcassel** [comment]
I was just working on some related documentation. I'll add some notes.

**Comment by dmcassel** [comment]
@xbonnamy-marklogic please take a look at https://marklogic-community.github.io/smart-mastering-core/docs/match-algorithms/#thesaurus and let me know if that addresses the need for documenting the thesaurus algorithm.

**Comment by dmcassel** [comment]
@xbonnamy-marklogic please review https://github.com/marklogic-community/smart-mastering-core/pull/211
