### ISSUE TITLE
Enhancement : collection pattern consistency when saving match and merge options

### ISSUE THREAD

**Issue by xbonnamy-marklogic** [marklogic-community/smart-mastering-core#213]
When saving match options using matcher.saveOptions(), options are saved with "mdm-match-options" collection.

However saving merge options using merging.saveOptions(), options are save with "mdm-merge" collection. It would be nice that when saving merge options, collection would be "mdm-merge-options".

**Comment by dmcassel** [comment]
Agreed, that would be more consistent.
