### ISSUE TITLE
Max-values of an array property should pertain to the array property itself, not the array contents

### ISSUE THREAD

**Issue by aajacobs** [marklogic-community/smart-mastering-core#239]
Currently, given:

Doc1.toObject().envelope.instance.myprop
```
[{
"code": "ABC", 
"startDate": "2018-01-01"
},
{
"code": "AB", 
"startDate": "--"
}]
```
and
Doc2.toObject().envelope.instance.myprop
```
[{
"code": "ABC", 
"startDate": "2018-01-01"
}, 
{
"code": "DEF", 
"startDate": "2018-09-09"
}]
```
It will return something like:
```
[{
"code": "ABC", 
"startDate": "2018-01-01"
}]
```
If you use max-values, it combines all the objects from the arrays together, and will, presumably by document order(?), keeping up to the max values.  This splits arrays apart in unpredictable ways for end-users without giving them means to have more granular merge controls at this child property level, even for custom merge actions.

Not sure the right way to solve this, but for now perhaps max-values should apply to the entire array itself, and not the contents of the array.  So max-values of 1 will keep an entire array.  

I'm not aware of anyone yet needing this functionality, and it will likely be superseded by work to allow merging at lower than top-level properties.

**Comment by ryanjdew** [comment]
See #253. Added "max-sources" attribute to merge options. This allows for the provide move specific intent. 

I could see in the future the need to select objects in an array across documents, sorted by an object property or something similar.
