### ISSUE TITLE
Can't open smart-mastering-core/examples/dhf-flow with DHF QuickStart v4.0.3

### ISSUE THREAD

**Issue by zi-dong** [marklogic-community/smart-mastering-core#255]
I downloaded the smart-mastering-core project, have run gradlew.bat mlDeploy under examples/dhf-flow directory, and can see the project successfully deployed to MarkLogic. However when I then try to use QuickStart v4.0.3 to view the project, I get the following message.

Congratulations on updating to version
4.0.3
But...your project doesn't seem to match this version of DHF!

Please update your project before proceeding onward! How to update a Hub Project

**Comment by ryanjdew** [comment]
Documentation on upgrading DHF can be found here: https://marklogic.github.io/marklogic-data-hub/understanding/upgrading/

**Comment by zi-dong** [comment]
I have followed the documentation on upgrading DHF, and the command line returns that there is nothing to be upgraded. However the error message still persist.

I've downloaded the project and deployed it without any modification. I've expected it to run as-is but it has not been the case.
