### ISSUE TITLE
Don't require sources in order to merge

### ISSUE THREAD

**Issue by aajacobs** [marklogic-community/smart-mastering-core#274]
In order for merging to work, docs have to have the following, even if the aren't using sources as a way to merge:
```
"envelope": {
    "headers": {
      "sources": [
        {
          "name": "MMIS"
        }
      ]
    }
```
If the merge options aren't using sources, this shouldn't be required.  If a merge option does specify a source, a user should be allowed to override where that is located.  If a merge option does specify a source but a user hasn't specified a location, and the document doesn't have the correct format, the framework should offer descriptive and helpful error messages that let them know what to do to fix it.

**Comment by ryanjdew** [comment]
Also, specifying the sources wrong (as an object instead of an array) causes items to be dropped during merging. We should ensure this issue should addresses that as well.
