### ISSUE TITLE
Non-deterministic  conflicting update bug when saving a merged document

### ISSUE THREAD

**Issue by anthony-gray** [marklogic-community/smart-mastering-core#318]
A merge document of [1.xml, 2.xml, 3.xml] is saved if matching on id1 and id2 for:
a.	1.xml with id1=1 and id2=A
b.	2.xml with id1=2 and id2=A
c.	3.xml with id1=1 and id2=C
d.	4.xml with id1=4 and id2=D

This save sometimes fails with a conflicting update error because the consolidation logic before saving tries to consolidate [1.xml, 2.xml], [1.xml, 2.xml, 3.xml], [1.xml, 3.xml] into [1.xml, 2.xml, 3.xml] in a buggy manner. One can start tracing the bug as starting at the let $merged-uris := map:keys($consolidated-merges) line in process.xqy's proc-impl:process-match-and-merge-with-options method.

**Comment by ryanjdew** [comment]
The processing logic ensures single operations per URI and 1.3.1 adds a unit test for the scenario described and the issue doesn't appear.

**Comment by anthony-gray** [comment]
Good. I will have to verify this.
