### ISSUE TITLE
Matching needs path support

### ISSUE THREAD

**Issue by anthony-gray** [marklogic-community/smart-mastering-core#320]
Matching does not support matching by path, but only element name. So, an expression like identifiers/identifierRecord[identifierTypeCode='MEDICAID_ID']/identifier is not supported. This means a data model itself needs to be changed in such cases to accommodate this shortcoming (e.g. add a uniquely named medicaidId element to every document).

**Comment by ryanjdew** [comment]
Thank you for the feedback. I will pursue adding this feature in a future release, with the understanding that this will require a path range index (http://docs.marklogic.com/guide/admin/range_index#id_40666) and will only work with exact matches (or only as flexible as collations will allow: http://docs.marklogic.com/guide/search-dev/encodings_collations#id_24886).

Are you currently using Smart Mastering as part of Data Hub 5 or as an independent library? Thanks!

**Comment by anthony-gray** [comment]
I’m using it independently. I do not intend to use DHF. In addition to path support, in general range indexes (element and path) should be supported. When dealing with 100K+ documents this makes a significant difference. However, I have filed a separate issue related to performance anyway.

**Comment by ryanjdew** [comment]
This will be possible in 1.3.1 with a path range index and a cts:path-reference being associated with the property.

**Comment by anthony-gray** [comment]
Nice. I will have to test this.

**Comment by eas0101** [comment]
@ryanjdew, I tried this and it's either not working or I'm doing something wrong. 

My options are:
```
{
 	"options": {
 		"propertyDefs": {
 			"property": [{
 				"namespace": "",
 				"localname": "lastName",
 				"name": "lastName"
 			}]
 		},
 		"algorithms": {
 			"algorithm": [	{
					"name": "dbl-metaphone",
					"function": "double-metaphone"
			}]
 		},
 		"scoring": {
 			"add": [{
 				"propertyName": "lastName",
 				"weight": "50"
 			}],
 			"expand": [{
 				"propertyName": "lastName",
 				"algorithmRef": "dbl-metaphone",
 				"weight": "5",
 				"dictionary": "name-dictionary.xml",
 				"distanceThreshold": "100"
 			}]
 		},
 		"collections": {
 			"content": ["FinalAssociate"]
 		},
 		"thresholds": {
 			"threshold": [{
 					"above": "5",
 					"label": "Possible Match"
 				},
 				{
 					"above": "100",
 					"label": "Likely Match"
 				},
 				{
 					"above": "150",
 					"label": "Definitive Match"
 				}
 			]
 		},
 		"tuning": {
 			"maxScan": "200"
 		}
 	}
 }
```

The document I am trying to  match has the following structure
`{
	"envelope": {
		"headers": {},
		"instance": {
			"fields": {
				"lastName": "Klien"
			},
			"beneficiaries": [{
					"lastName": "Michales"
				},
				{
					"lastName": "Ellis"
				}
			]
		}
	}
}`
> 
In my result, I see the following
`<results total="1" page-length="200" start="1">
<boost-query>
<cts:or-query xmlns:cts="http://marklogic.com/cts">
<cts:json-property-value-query weight="50">
<cts:property>lastName</cts:property>
<cts:value xml:lang="en">Klien</cts:value>
<cts:value xml:lang="en">Michales</cts:value>
<cts:value xml:lang="en">Ellis</cts:value>
<cts:option>case-insensitive</cts:option>
</cts:json-property-value-query>
</cts:or-query>
</boost-query>
<match-query>
<cts:or-query xmlns:cts="http://marklogic.com/cts">
<cts:json-property-value-query weight="0">
<cts:property>lastName</cts:property>
<cts:value xml:lang="en">Klien</cts:value>
<cts:value xml:lang="en">Michales</cts:value>
<cts:value xml:lang="en">Ellis</cts:value>
<cts:option>case-insensitive</cts:option>
</cts:json-property-value-query>
</cts:or-query>
</match-query>`
