### ISSUE TITLE
Fuzzy matching (e.g. double-metaphone) should dynamically generate dictionaries

### ISSUE THREAD

**Issue by anthony-gray** [marklogic-community/smart-mastering-core#321]
Fuzzy matching (e.g. double-metaphone) should dynamically generate dictionaries because the domain for a given match element is the values of the element in the system at the start of matching. This currently does not seem to be working.

**Comment by ryanjdew** [comment]
@anthony-gray Are you using this library independently or as an incorporated part of Data Hub 5? There was a method that allowed would create a dictionary if it didn't exist and there was a range index on the field, as part of storing options. 

This logic isn't called as part of Data Hub 5, as the options are stored differently. A dictionary can be generated using cts.values on a range index and passing those values into spell.makeDictionary. (https://docs.marklogic.com/spell.makeDictionary)

**Comment by anthony-gray** [comment]
I’m using it independently. I do not intend to use DHF. Matching should do this automatically by default because this should be the most common use case in the context of matching documents in a particular database using fields of documents in that database. Passing/supplying a dictionary should be optional. I should not have to call a method to generate a dictionary. All I should have to do is specify in the match configuration the arguments for fuzzy matching and it should just work. If there is a configuration option that toggles dictionary generation please let me know.

**Comment by ryanjdew** [comment]
In version 1.3.1. dictionaries that don't already exist will be created from indexes that are associated with a property if a cts:reference is provided.

**Comment by anthony-gray** [comment]
Okay. I will have to test this.
