### ISSUE TITLE
Publish and depend on smart-mastering-code like ml-unit-test

### ISSUE THREAD

**Issue by rjrudin** [marklogic-community/smart-mastering-core#47]
Should be able to follow the same approach as ml-unit-test, where a client project can use it like this:

    mlRestApi "com.marklogic:smart-mastering-code:(version)"

And not have to do anything else.

Also, as part of publishing the project, jcenter requires there to be a "sources" jar, which is basically the same as the regular jar/zip - that's the approach I'm using for ml-unit-test.

I'll get a PR together for this soon.

**Comment by dmcassel** [comment]
Goal is to simplify this set of instructions: https://github.com/marklogic-community/smart-mastering-core#instructions

**Comment by dmcassel** [comment]
PR accepted
