### ISSUE TITLE
Not able to add merge configuration using Rest api in minimal-project.

### ISSUE THREAD

**Issue by somaiyahr** [marklogic-community/smart-mastering-core#82]
I am not able to add merge configuration to minimal-project using sm-merge-options Rest api, Although I was successful in adding match configuration.

Steps followed to setup.
1. Cloned the Smart mastering core repository and ran  gradle.bat publishToMavenLocal command
2.  Smart mastering added to local maven repository at location .m2\repository\com\marklogic\community\smart-mastering-core\1.0.0-beta.1.
3. Traversed to minimal-project and ran gradle mlDeploy
4. Verified the resources by hitting the end point
http://localhost:8800/v1/config/resources
5. Access the below endpoint to put/post match & merge options
http://localhost:8800/v1/resources/sm-match-options?rs:name=mlw-match
http://localhost:8800/v1/resources/sm-merge-options?rs:name=mlw-merge
[Smart_Mastering_Resources.txt](https://github.com/marklogic-community/smart-mastering-core/files/2137252/Smart_Mastering_Resources.txt)
[mdm-merge-options.txt](https://github.com/marklogic-community/smart-mastering-core/files/2137255/mdm-merge-options.txt)

Let me know if I missed any step in setting the project.

**Comment by dmcassel** [comment]
Thanks for reporting the problem. What happened when you tried to PUT or POST to sm-merge-options? Please check the error log for the app server on 8800. 
What version of MarkLogic are you running?

**Comment by somaiyahr** [comment]
I tried to PUT or POST to sm-merge-options from postman rest client and it return response code 204 No Content. No error log for the app server on 8800, blank file. 
Current MarkLogic version in use is 9.0-5.1

**Comment by paxtonhare** [comment]
@somaiyahr can you paste your options files?

**Comment by somaiyahr** [comment]
Mdm merge options attached in set up steps..

**Comment by somaiyahr** [comment]
Issue got resolved: It was namespace issue mdm-merge-options.xml was pointing to incorrect namespace so was not able to add it through rest api.
