### ISSUE TITLE
deployMatchOptions FAILED

### ISSUE THREAD

**Issue by RubinaV** [marklogic-community/smart-mastering-core#96]
Team,

I am facing below mentioned issue while running "gradle prepDemo" from \examples\smart-mastering.

> Task :deployMatchOptions FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':deployMatchOptions'.
> javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?

Is there any configuration changes needs to be done for this ?

**Comment by rjrudin** [comment]
Which branch is that on? I don't see an "examples/smart-mastering" directory on master or develop.

My initial guess is that you may have SSL enabled on port 8000 or 8002 in MarkLogic.

**Comment by popzip** [comment]
Hi @RubinaV - any update on this?

**Comment by popzip** [comment]
We haven't been able to reproduce so I am closing, but feel free to re-open.
